function [XDEN,wDEC] = func_denoise_sw2d(X)
% FUNC_DENOISE_SW2D Saved Denoising Process.
%   X: matrix of data
%   -----------------
%   XDEN: matrix of denoised data
%   wDEC: stationary wavelet decomposition

%  Auto-generated by Wavelet Toolbox on 07-Dec-2016 14:38:05

% Analysis parameters.
%---------------------
wname = 'haar';
level = 5;

% Denoising parameters.
%-----------------------
% meth = 'sqtwolog';
% scal_OR_alfa = one;
sorh = 's';    % Specified soft or hard thresholding
thrSettings =  [...
    1.649432013769363      3.323855421686744      5.860481927710737     10.811641566265166     29.243836058519832 ; ...
    0.959629000000000      1.367699300000001      2.075847676419969      5.263170412500003     10.324699870912241 ; ...
    1.624440619621339      2.693214150000001      4.790017211703969     11.168029259896684     15.519972703125013   ...
    ];
roundFLAG = false;

% Decompose using SWT2.
%---------------------
wDEC = swt2(X,level,wname);

% Denoise.
%---------
permDir = [1 3 2];
for j = 1:level
    for kk=1:3
        ind = (permDir(kk)-1)*level+j;
        thr = thrSettings(kk,j);
        wDEC(:,:,ind) = wthresh(wDEC(:,:,ind),sorh,thr);
    end
end

% Reconstruct the denoise signal using ISWT2.
%-------------------------------------------
XDEN = iswt2(wDEC,wname);
if roundFLAG , XDEN = round(XDEN); end
